
-- CREATION OF TABLE INVOICE
CREATE TABLE INVOICE
(	
ORDER_REF VARCHAR2(8),
INVOICE_REFERENCE 	VARCHAR2(12), 
INVOICE_DATE 		DATE, 
INVOICE_STATUS 		VARCHAR2(10), 
INVOICE_HOLD_REASON VARCHAR2(100), 
INVOICE_AMOUNT 		NUMBER(10,2), 
INVOICE_DESCRIPTION VARCHAR2(100),
PRIMARY KEY (ORDER_REF, INVOICE_REFERENCE)
) ;

-- Does not work even if using NVL(INVOICE_REFERENCE,'NULL_VALUE') in the insert as ORDER_REF has duplicate data