-- INVOICE
-- CREATION OF SEQUENCE
CREATE SEQUENCE INVOICE_ID_SEQ START WITH 1 INCREMENT BY 1;

-- CREATION OF TABLE INVOICE
CREATE TABLE INVOICE
(	
INVOICE_ID  NUMBER DEFAULT INVOICE_ID_SEQ.NEXTVAL,
INVOICE_REFERENCE 	VARCHAR2(12), 
INVOICE_DATE 		DATE, 
INVOICE_STATUS 		VARCHAR2(10), 
INVOICE_HOLD_REASON VARCHAR2(100), 
INVOICE_AMOUNT 		NUMBER(10,2), 
INVOICE_DESCRIPTION VARCHAR2(100),
PRIMARY KEY (INVOICE_ID)
) ;