-- Inserting data into SUPPLIER
INSERT INTO SUPPLIER (
    SUPPLIER_NAME,
    SUPP_CONTACT_FIRST_NAME,
	SUPP_CONTACT_LAST_NAME,
	SUPPLIER_building_number,
	SUPPLIER_street,
	SUPPLIER_TOWN,
	SUPPLIER_COUNTRY,
	SUPP_CONTACT_NUMBER1,
	SUPP_CONTACT_NUMBER2, 	
	SUPP_EMAIL        		
)
SELECT 
    DISTINCT SUPPLIER_NAME,
    MAX(REGEXP_SUBSTR(SUPP_CONTACT_NAME, '[^ ]+', 1, 1)) AS SUPP_CONTACT_FIRST_NAME,
    MAX(REGEXP_SUBSTR(SUPP_CONTACT_NAME, '[^ ]+', 1, 2)) AS SUPP_CONTACT_LAST_NAME,
	MAX(SUPPLIER_building_number) AS SUPPLIER_building_number,
	MAX(SUPPLIER_street) AS SUPPLIER_street,
	MAX(SUPPLIER_TOWN) AS SUPPLIER_TOWN,
	MAX(SUPPLIER_COUNTRY) AS SUPPLIER_COUNTRY,
	MAX(SUPP_CONTACT_NUMBER1) AS SUPP_CONTACT_NUMBER1,
	MAX(SUPP_CONTACT_NUMBER2) AS SUPP_CONTACT_NUMBER2,
	MAX(SUPP_EMAIL) AS SUPP_EMAIL
    
FROM BCM_ORDER_MGT_CLEANED b
WHERE NOT EXISTS 
(
    SELECT 1
    FROM SUPPLIER s
    WHERE 
		s.SUPPLIER_NAME = b.SUPPLIER_NAME
)
GROUP BY SUPPLIER_NAME;
commit;

/*
The DISTINCT keyword ensures that only unique SUPPLIER_NAME values are considered.
The MAX function is used to select one of the values for each column. 
    If there's only one value for each SUPPLIER_NAME, MAX effectively selects that value.
The GROUP BY SUPPLIER_NAME groups the data by SUPPLIER_NAME.
*/

