--ORDERS

-- INSERT OF DATA INTO ORDERS FROM BCM_ORDER_MGT AND INVOICE
INSERT INTO ORDERS (
    ORDER_REF,
    ORDER_DATE,
    SUPPLIER_NAME,
	INVOICE_ID,
    ORDER_TOTAL_AMOUNT,
    ORDER_DESCRIPTION,
    ORDER_STATUS,
    ORDER_LINE_AMOUNT
)
SELECT
    ORDER_REF,
    ORDER_DATE,
    SUPPLIER_NAME,
    INVOICE_ID,
	ORDER_TOTAL_AMOUNT,
    ORDER_DESCRIPTION,
    ORDER_STATUS,
    ORDER_LINE_AMOUNT
FROM
    BCM_ORDER_MGT_CLEANED b
JOIN
-- Joining table BCM_ORDER_MGT and INVOICE
-- ISSUES here due to the null values found on table INVOICE
    INVOICE i ON
        i.INVOICE_REFERENCE = b.INVOICE_REFERENCE
        AND i.MAIN_ID = b.MAIN_ID
-- Checking if rows already exist before inserting
WHERE NOT EXISTS (
    SELECT 1
    FROM ORDERS o
    WHERE
        o.ORDER_REF = b.ORDER_REF
        AND o.INVOICE_ID = i.INVOICE_ID
)
-- validating if supplier_name exist in supplier table
AND EXISTS (
	SELECT 1
	FROM SUPPLIER s
	WHERE s.SUPPLIER_NAME = b.SUPPLIER_NAME
)    
ORDER BY b.ORDER_REF;